rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 1.9.2
#  - jruby      # Running out of memory on Travis
#  - ruby-head  # RedCloth does not compile on head
#  - 1.8.6      # unsupported

script: "bundle exec rake"
env: "CI=1 SUITE=1 "
